export const CREATE_QUOTE_AND_BUY_FORM = "CREATE_QUOTE_AND_BUY_FORM";
export const CREATE_ENDORSEMENT_FORM = "CREATE_ENDORSEMENT_FORM";
export const CREATE_CLAIMS_FORM = "CREATE_CLAIMS_FORM";
export const CREATE_CONTACT_FORM = "CREATE_CONTACT_FORM";

export const UPSERT_ANSWER = "UPSERT_ANSWER";

// Navigation
export const NAVIGATE_TO_SECTION = "NAVIGATE_TO_SECTION";
export const NEXT_SECTION = "NEXT_SECTION";
export const PREV_SECTION = "PREV_SECTION";
export const SET_VALID_SECTION_URL_PARAM = "SET_VALID_SECTION_URL_PARAM";
export const SET_SECTION_URL_PARAM = "SET_SECTION_URL_PARAM";
export const REMOVE_VALID_SECTION_URL_PARAM = "REMOVE_VALID_SECTION_URL_PARAM";

// Claim
export const SUBMIT_CLAIM_REQUEST = "SUBMIT_CLAIM_REQUEST";
export const SUBMIT_CLAIM_SUCCESS = "SUBMIT_CLAIM_SUCCESS";

// Contact Us
export const SUBMIT_CONTACT_US_REQUEST = "SUBMIT_CONTACT_US_REQUEST";
export const SUBMIT_CONTACT_US_SUCCESS = "SUBMIT_CONTACT_US_SUCCESS";

// Endorsement
export const CREATE_ENDORSEMENT_REQUEST = "CREATE_ENDORSEMENT_REQUEST";
export const CREATE_ENDORSEMENT_SUCCESS = "CREATE_ENDORSEMENT_SUCCESS";
export const UPDATE_ENDORSEMENT_REQUEST = "UPDATE_ENDORSEMENT_REQUEST";
export const UPDATE_ENDORSEMENT_SUCCESS = "UPDATE_ENDORSEMENT_SUCCESS";
export const FINALISE_ENDORSEMENT_REQUEST = "FINALISE_ENDORSEMENT_REQUEST";
export const FINALISE_ENDORSEMENT_SUCCESS = "FINALISE_ENDORSEMENT_SUCCESS";
export const PREPOPULATED_SUCCESS = "PREPOPULATED_SUCCESS";

// Form
export const CREATE_FORM_REQUEST = "CREATE_FORM_REQUEST";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const RESET_FORM = "RESET_FORM";
export const SET_FORM_TYPE = "SET_FORM_TYPE";
export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";
export const SUBMIT_FORM_ERROR = "SUBMIT_FORM_ERROR";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";

// Fraud
export const FRAUD_CHECK_REQUEST = "FRAUD_CHECK_REQUEST";
export const FRAUD_CHECK_SUCCESS = "FRAUD_CHECK_SUCCESS";
export const FRAUD_CHECK_ERROR = "FRAUD_CHECK_ERROR";

// Lead
export const CREATE_LEAD_REQUEST = "CREATE_LEAD_REQUEST";
export const CREATE_LEAD_SUCCESS = "CREATE_LEAD_SUCCESS";
export const CREATE_LEAD_ERROR = "CREATE_LEAD_ERROR";
export const UPDATE_LEAD_REQUEST = "UPDATE_LEAD_REQUEST";
export const UPDATE_LEAD_SUCCESS = "UPDATE_LEAD_SUCCESS";
export const UPDATE_LEAD_ERROR = "UPDATE_LEAD_ERROR";
export const DELETE_LEAD_REQUEST = "DELETE_LEAD_REQUEST";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const DELETE_LEAD_ERROR = "DELETE_LEAD_ERROR";

// Payment
export const SET_CREDIT_CARD_TOKEN = "SET_CREDIT_CARD_TOKEN";
export const GET_CUSTOMER_CLIENT_TOKEN_REQUEST = "GET_CUSTOMER_CLIENT_TOKEN_REQUEST";
export const GET_CUSTOMER_CLIENT_TOKEN_SUCCESS = "GET_CUSTOMER_CLIENT_TOKEN_SUCCESS";
export const GET_CUSTOMER_CLIENT_TOKEN_ERROR = "GET_CUSTOMER_CLIENT_TOKEN_ERROR";
export const GET_RENEWALS_REQUEST = "GET_RENEWALS_REQUEST";
export const GET_RENEWALS_SUCCESS = "GET_RENEWALS_SUCCESS";
export const GET_RENEWALS_ERROR = "GET_RENEWALS_ERROR";


// Policy
export const GET_POLICY_AND_POLICYHOLDER_IDS_REQUEST = "GET_POLICY_AND_POLICYHOLDER_IDS_REQUEST";
export const GET_POLICY_AND_POLICYHOLDER_IDS_SUCCESS = "GET_POLICY_AND_POLICYHOLDER_IDS_SUCCESS";
export const GET_POLICY_AND_POLICYHOLDER_IDS_ERROR = "GET_POLICY_AND_POLICYHOLDER_IDS_ERROR";
export const GET_POLICY_REQUEST = "GET_POLICY_REQUEST";
export const GET_POLICY_SUCCESS = "GET_POLICY_SUCCESS";
export const GET_POLICY_ERROR = "GET_POLICY_ERROR";
export const GET_POLICYHOLDERS_REQUEST = "GET_POLICYHOLDERS_REQUEST";
export const GET_POLICYHOLDERS_SUCCESS = "GET_POLICYHOLDERS_SUCCESS";
export const GET_POLICYHOLDERS_ERROR = "GET_POLICYHOLDERS_ERROR";

export const GET_POLICIES_AND_POLICYHOLDERS_REQUEST = "GET_POLICIES_AND_POLICYHOLDERS_REQUEST";
export const GET_POLICIES_AND_POLICYHOLDERS_SUCCESS = "GET_POLICIES_AND_POLICYHOLDERS_SUCCESS";
export const GET_POLICIES_AND_POLICYHOLDERS_ERROR = "GET_POLICIES_AND_POLICYHOLDERS_ERROR";

// Price
export const GET_QUOTE_PRICE_SUCCESS = "GET_QUOTE_PRICE_SUCCESS";
export const GET_QUOTE_PRICE_REQUEST = "GET_QUOTE_PRICE_REQUEST";
export const GET_QUOTE_PRICE_ERROR = "GET_QUOTE_PRICE_ERROR";
export const GET_QUOTE_PRICE_RESET = "GET_QUOTE_PRICE_RESET";
export const GET_ENDORSEMENT_PRICE_REQUEST = "GET_ENDORSEMENT_PRICE_REQUEST";
export const GET_ENDORSEMENT_PRICE_SUCCESS = "GET_ENDORSEMENT_PRICE_SUCCESS";
export const GET_ENDORSEMENT_PRICE_ERROR = "GET_ENDORSEMENT_PRICE_ERROR";
export const SET_PREVIOUS_PRICES = "SET_PREVIOUS_PRICES";

export const SET_PRICING_QUOTE = "SET_PRICING_QUOTE";
export const CLEAR_PRICING_QUOTE = "CLEAR_PRICING_QUOTE";
export const SET_PRICING_ENDORSEMENT = "SET_PRICING_ENDORSEMENT";
export const CLEAR_PRICING_ENDORSEMENT = "CLEAR_PRICING_ENDORSEMENT";
export const SET_PRICING_RENEWALS = "SET_PRICING_RENEWALS";


// Question Set
export const GET_QUESTION_SET_REQUEST = "GET_QUESTION_SET_REQUEST";
export const GET_QUESTION_SET_ERROR = "GET_QUESTION_SET_ERROR";
export const GET_QUESTION_SET_SUCCESS = "GET_QUESTION_SET_SUCCESS";

// Quote
export const CREATE_QUOTE_REQUEST = "CREATE_QUOTE_REQUEST";
export const CREATE_QUOTE_SUCCESS = "CREATE_QUOTE_SUCCESS";
export const CREATE_QUOTE_ERROR = "CREATE_QUOTE_ERROR";
export const UPDATE_QUOTE_REQUEST = "UPDATE_QUOTE_REQUEST";
export const UPDATE_QUOTE_SUCCESS = "UPDATE_QUOTE_SUCCESS";
export const UPDATE_QUOTE_ERROR = "UPDATE_QUOTE_ERROR";
export const FINALISE_QUOTE_REQUEST = "FINALISE_QUOTE_REQUEST";
export const FINALISE_QUOTE_SUCCESS = "FINALISE_QUOTE_SUCCESS";
export const FINALISE_QUOTE_ERROR = "FINALISE_QUOTE_ERROR";

// Underwriting
export const PROCESS_UNDERWRITING_REQUEST = "PROCESS_UNDERWRITING_REQUEST";
export const PROCESS_UNDERWRITING_SUCCESS = "PROCESS_UNDERWRITING_SUCCESS";
export const PROCESS_UNDERWRITING_ERROR = "PROCESS_UNDERWRITING_ERROR";
export const UNDERWRITING_DECLINE = "UNDERWRITING_DECLINE";

export const CLEAR_POLICY_CHANGES = "CLEAR_POLICY_CHANGES";

// ORM

// AnswerGroup
export const CREATE_ANSWER_GROUP = "CREATE_ANSWER_GROUP";
export const UPDATE_ANSWER_GROUP = "UPDATE_ANSWER_GROUP";
export const DELETE_ANSWER_GROUP = "DELETE_ANSWER_GROUP";
export const CREATE_RELATIONSHIP = "CREATE_RELATIONSHIP";
export const DELETE_RELATIONSHIP = "DELETE_RELATIONSHIP";
export const DELETE_GROUP = "DELETE_GROUP";

// Peril
export const ADD_PERIL = "ADD_PERIL";
export const UPDATE_PERIL = "UPDATE_PERIL";
export const REMOVE_PERIL = "REMOVE_PERIL";
export const DELETE_PERIL = "DELETE_PERIL";
